[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 20_000
solc = "0.8.23"

fs_permissions = [{ access = "read-write", path = "./"}]

etherscan_api_key = "2WRUJ9EEBUYAZQRAPRJPXDZ6WA3VWQU4B4"
remappings = [
  "ethereum-vault-connector/=lib/ethereum-vault-connector/src"
]
gas_reports = ["*"]


[profile.default.fmt]
ignore = [
    "src/EVault/EVault.sol",
    "src/EVault/shared/Storage.sol"
]


[profile.default.fuzz]
max_test_rejects = 1_000_000
seed = "0xee1d0f7d9556539a9c0e26aed5e63556"
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
